language: node_js
node_js:
  - "iojs"
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  - npm install -g grunt grunt-cli
  - npm install --save-dev App/
install: npm install
before_script: grunt build
before_deploy:
  - ls -R
  - cd build/beaglebone-getting-started/linux64
  - zip ../beagle-getting-started_linux64.zip *
  - cd ../../..
deploy:
  provider: releases
  api_key: $GITHUBDEPLOY
  file: "build/beaglebone-getting-started/beagle-getting-started_linux64.zip"
  skip_cleanup: true
  on:
    tags: true
