language: node_js
os: osx
node_js:
  - "iojs"
before_install:
  - brew update
  - npm install -g grunt grunt-cli
  - npm install --save-dev App/
install: npm install
before_script: grunt build
before_deploy:
  - ls -R
  - cd build/beaglebone-getting-started/osx64
  - zip ../beagle-getting-started_osx64.zip *
  - cd ../../..
deploy:
  provider: releases
  api_key: "$GITHUBDEPLOY"
  file: "build/beaglebone-getting-started/beagle-getting-started_osx64.zip"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    - secure: oPrtRljDa9KurCqGgpqxIl/3uidn5UMYMSBxcq3Njha95QuIL5g7+3F+chi6uhdH1FYvtm3KUW9MOCczRh3UBRTJdvQDRDx4K6vFiGVu/sV+lihqHXx+pGMFC+K8SmtC8H2VEPSF6/WWpuj4sRu8YTeML9VsNcH8lH/F7blm9oNZvW+GM2HJKXTfMwDXsl8AP8i5sc3wKaG+j8rI6v020vptx+M674gctyU9yzY4xOWqsYMtHf5IlFtFeEvBC4MsYW8VrE8zuaeYRm8MpY7dUOFZR/y9zSYA5ijFaxLnoKzD2HpInsNJNaitvE/rIocj/VbAGtEBx2I7gxwKf1OjGFjgFJDmKCrE+JKvONGSUp4v0IeTj04NlRoc9k56N7xo3LCIQd3X5JJk8+8mKn9bdYCRUGLzP3DQt5DNoNwgzjiiSEf9UzNZEnfNawESzrkegLKWKB+0r5/oRM2fbIQhKymYfUsAo6TPl8QaIAUhFfTJDHxbhHcSlN56RUD966J6XOFeV6c3W8gbTjL8h15Q8Js+p/O8LIOExN25zwwOlnInRWcJN1JxT4TongcoS57Rm0O7sz/GMF/0161GJSwRaS7RfwMcP2zpsEu/VgtAUjSwqtT9V7xwuYZsCAPX7mx25m259b7wcaEFpBh1QU5QsVN9LkVj8kLaxBeyLoQvR3M=


