# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install

# Since we don't have a solution/project
build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # file against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerSehll" # Pass comment to PS for easier debugging
  - cmd: npm test

# matrix:
  # fast_finish: true
  # allow_failures:
    # -nodejs_version: 0.12

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json        # npm cache
  - node_modules -> package.json                                       # local npm modules